package com.example.jiaofenghangks.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.jiaofenghangks.bean.AdDbbean;

import com.example.jiaofenghangks.dao.AdDbbeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig adDbbeanDaoConfig;

    private final AdDbbeanDao adDbbeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        adDbbeanDaoConfig = daoConfigMap.get(AdDbbeanDao.class).clone();
        adDbbeanDaoConfig.initIdentityScope(type);

        adDbbeanDao = new AdDbbeanDao(adDbbeanDaoConfig, this);

        registerDao(AdDbbean.class, adDbbeanDao);
    }
    
    public void clear() {
        adDbbeanDaoConfig.clearIdentityScope();
    }

    public AdDbbeanDao getAdDbbeanDao() {
        return adDbbeanDao;
    }

}
